# nginx proxy address - http://172.17.0.1:8089

name: organizr
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  organizr:
    image: organizr/organizr:latest
    pull_policy: always
    container_name: organizr-app
    restart: always
    logging: *default-logging
    networks:
      - organizr
    ports:
      - "172.17.0.1:8089:80"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      fpm: "false"
    volumes:
      - ./volumes/config/organizr:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  organizr:
    external: false
