# nginx proxy address - http://172.17.0.1:8089

name: organizr
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  organizr:
    image: organizr/organizr:latest
    pull_policy: always
    container_name: organizr-app
    restart: always
    logging: *default-logging
    networks:
      - organizr
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8089:80"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      fpm: "false"
      CONTAINER_NAME: organizr-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - ./volumes/config/organizr:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://organizr-app:80'
      - 'cloudflare.hostname=organizr.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.organizr-app.entrypoints=http'
      - 'traefik.http.routers.organizr-app-secure.tls=true'
      - 'traefik.http.routers.organizr-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.organizr-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.organizr-app.middlewares=organizr-app-https-redirect'
      - 'traefik.http.routers.organizr-app-secure.entrypoints=https'
      - 'traefik.http.routers.organizr-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.organizr-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.organizr-app-secure.service=organizr-app'
      - 'traefik.http.services.organizr-app.loadbalancer.server.port=80'

networks:
  organizr:
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
